### ISSUE TITLE
want to covid-tracker and predicator website 

### ISSUE THREAD

**Issue by ayushranjan2806** [aryangarg08/Hacktoberfest_2022_Web_Dev_Projects#38]
the idea of project to stop the spread of covid virus .In this project there is two 
module 1st one is for tracking and 2nd is used for detection .For using this idea 
we have to control the spread of corona virus by using tracking 
,detection,testing and one day world is free from covid -19. @aryangarg08 assign me this project

**Comment by aryangarg08** [comment]
Done
